#!/bin/bash
# parameter 1: port
# parameter 2: metric name
# parameter 3...: valid value list

set -eu

port=$1
metric_name=$2

metric=$(curl -s http://127.0.0.1:$port/metrics | grep $metric_name | awk '{print $2}')
shift 2
for pattern in "$@"; do
    if [ "$metric" == "${pattern}" ]; then
        exit 0
    fi
done

echo "metric $metric_name has invalid value $metric"
exit 1
