#!/bin/sh

set -eu

workdir=$1
config=$2

binary=$PWD/bin/dm-syncer

PWD=$(pwd)

mkdir -p $workdir/log

format=""
meta=""
name=""

if [ "$#" -ge 5 ]; then
    meta="--meta=$3"
    format=$4
    name="--name=$5"
fi

cd $workdir
echo "$binary --log-file="$workdir/log/dm-syncer.log" --config="$config" $meta $format >> $workdir/log/stdout.log 2>&1 &"
$binary -L=Debug --log-file="$workdir/log/dm-syncer.log" --config="$config" $name $meta $format >> $workdir/log/stdout.log 2>&1 &
cd $PWD

