#!/bin/sh
# parameter 1: tidb port

set -eu

PORT=$1
TEST_DIR=/tmp/dm_test

echo "Starting TiDB on port ${PORT}"
bin/tidb-server \
    -P ${PORT} \
    --store mocktikv \
    --log-file "$TEST_DIR/tidb.log" &

echo "Verifying TiDB is started..."
i=0
while ! mysql -uroot -h127.0.0.1 -P${PORT} --default-character-set utf8 -e 'select * from mysql.tidb;'; do
    i=$((i+1))
    if [ "$i" -gt 10 ]; then
        echo 'Failed to start TiDB'
        exit 1
    fi
    sleep 2
done