#!/bin/sh

set -eu

workdir=$1
config=$2

binary=$PWD/bin/dm-syncer

PWD=$(pwd)

mkdir -p $workdir/log

format=""

if [ "$#" -ge 3 ]; then
    format=$3
fi

cd $workdir
echo "$binary --log-file="$workdir/log/dm-syncer.log" --config="$config" $format >> $workdir/log/stdout.log 2>&1 &"
$binary -L=Debug --log-file="$workdir/log/dm-syncer.log" --config="$config" $format >> $workdir/log/stdout.log 2>&1 &
cd $PWD

