codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 4
  round: down

  status:
    project:
      default:
        threshold: 3 #Allow the coverage to drop by threshold%, and posting a success status.
    patch:
      default:
        target: 0%
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "LICENSES"
  - "*_test.go"
  - "*.pb.go"
  - ".git"
  - "*.yaml"
  - "*.toml"
  - "*.md"
  - "cmd/.*"
  - "docs/.*"
