{
 "title": "Test-Cluster-DM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "task",
    "query": "label_values(dm_worker_task_state, task)"
   },
   {
    "name": "source",
    "query": "label_values(dm_worker_task_state, source_id)"
   },
   {
    "name": "instance",
    "query": "label_values(dm_worker_task_state{task=~\"$task\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "overview (multiple instances)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "task state",
   "type": "graph",
   "description": "The current state of subtasks in instances.\n\n0: Invalid\n\n1: New\n\n2: Running\n\n3: Paused\n\n4: Stopped\n\n5: Finished",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dm_worker_task_state{task=~\"$task\"}"
    }
   ]
  },
  {
   "title": "storage capacity",
   "type": "graph",
   "description": "The storage capacity of the disk occupied by the relay log",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dm_relay_space{type=\"capacity\"}"
    }
   ]
  },
  {
   "title": "storage remain",
   "type": "graph",
   "description": "The remaining storage capacity of the disk occupied by the relay log",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dm_relay_space{type=\"available\"}"
    }
   ]
  },
  {
   "title": "binlog file gap between master and relay",
   "type": "graph",
   "description": "The number of binlog files in the relay log that are behind the upstream master",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dm_relay_binlog_file{node=\"master\"} - ON(instance, job) dm_relay_binlog_file{node=\"relay\"}"
    }
   ]
  },
  {
   "title": "load progress",
   "type": "graph",
   "description": "The data import process percentage of Loader. The value range is 0% ~ 100%",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "dm_loader_progress{task=~\"$task\"}"
    }
   ]
  },
  {
   "title": "binlog file gap between master and syncer",
   "type": "graph",
   "description": "The number of binlog files in binlog replication unit that are behind the master",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dm_syncer_binlog_file{task=~\"$task\", node=\"master\"} - ON(instance, task, job) dm_syncer_binlog_file{task=~\"$task\", node=\"syncer\"}"
    }
   ]
  },
  {
   "title": "shard lock resolving",
   "type": "graph",
   "description": "Is waiting shard DDL lock to be resolved, >0 means waiting",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dm_syncer_shard_lock_resolving{task=~\"$task\"}"
    }
   ]
  },
  {
   "title": "operate error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "before any operate error",
     "type": "graph",
     "description": "The number of error happens before operate",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"BeforeAnyOp\"}"
      }
     ]
    },
    {
     "title": "source bound error",
     "type": "graph",
     "description": "The number of error happens in operate source bound",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"SourceBound\"}"
      }
     ]
    },
    {
     "title": "start error",
     "type": "graph",
     "description": "The number of error happens in operate start",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Start\"}"
      }
     ]
    },
    {
     "title": "pause error",
     "type": "graph",
     "description": "The number of error happens in operate pause",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Pause\"}"
      }
     ]
    },
    {
     "title": "resume error",
     "type": "graph",
     "description": "The number of error happens in operate resume",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Resume\"}"
      }
     ]
    },
    {
     "title": "auto-resume error",
     "type": "graph",
     "description": "The number of error happens in operate auto-resume",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"AutoResume\"}"
      }
     ]
    },
    {
     "title": "update error",
     "type": "graph",
     "description": "The number of error happens in operate update",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Update\"}"
      }
     ]
    },
    {
     "title": "stop error",
     "type": "graph",
     "description": "The number of error happens in operate stop",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_worker_operate_error{type=\"Stop\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "task state",
     "type": "singlestat",
     "description": "The current state of the subtask in the instance",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_worker_task_state{task=~\"$task\",source_id=~\"$source\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "relay log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "storage capacity",
     "type": "singlestat",
     "description": "The storage capacity of the disk occupied by the relay log",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_relay_space{instance=~\"$instance\", type=\"capacity\"}"
      }
     ]
    },
    {
     "title": "storage remain",
     "type": "singlestat",
     "description": "The remaining storage capacity of the disk occupied by the relay log",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_relay_space{instance=~\"$instance\", type=\"available\"}"
      }
     ]
    },
    {
     "title": "process exits with error",
     "type": "singlestat",
     "description": "The relay log encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_relay_exit_with_error_count{instance=~\"$instance\"}[30m])"
      }
     ]
    },
    {
     "title": "relay log data corruption",
     "type": "singlestat",
     "description": "The number of corrupted relay log files",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_relay_data_corruption{instance=~\"$instance\"}[30m])"
      }
     ]
    },
    {
     "title": "fail to read binlog from master",
     "type": "singlestat",
     "description": "The number of errors encountered when the relay log reads the binlog from the upstream MySQL",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_relay_read_error_count{instance=~\"$instance\"}[30m])"
      }
     ]
    },
    {
     "title": "fail to write relay log",
     "type": "singlestat",
     "description": "The number of errors encountered when the relay log writes the binlog to disks",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_relay_write_error_count{instance=~\"$instance\"}[30m])"
      }
     ]
    },
    {
     "title": "binlog file index",
     "type": "graph",
     "description": "The largest index number of relay log files. E.g. \"value = 1\" indicates \"mysql-bin.000001\"",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{instance=~\"$instance\", node=\"master\"}",
       "legendFormat": "master"
      },
      {
       "expr": "dm_relay_binlog_file{instance=~\"$instance\", node=\"relay\"}",
       "legendFormat": "relay"
      }
     ]
    },
    {
     "title": "binlog file gap between master and relay",
     "type": "graph",
     "description": "The number of binlog files in the relay log that are behind the upstream master",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{instance=~\"$instance\", node=\"master\"} - ON(instance, job) dm_relay_binlog_file{instance=~\"$instance\", node=\"relay\"}"
      }
     ]
    },
    {
     "title": "binlog pos",
     "type": "graph",
     "description": "The write offset of the latest relay log file",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_pos{instance=~\"$instance\", node=\"master\"}",
       "legendFormat": "master"
      },
      {
       "expr": "dm_relay_binlog_pos{instance=~\"$instance\", node=\"relay\"}",
       "legendFormat": "relay"
      }
     ]
    },
    {
     "title": "read binlog event duration",
     "type": "graph",
     "description": "The duration that the relay log reads binlog event from the upstream MySQL (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_relay_read_binlog_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_relay_read_binlog_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_relay_read_binlog_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "write relay log duration",
     "type": "graph",
     "description": "The duration that the relay log writes binlog event into the disks each time (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_relay_write_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_relay_write_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_relay_write_duration_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "binlog event size",
     "type": "graph",
     "description": "The size of a single binlog event that the relay log writes into the disks",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_relay_write_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_relay_write_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_relay_write_size_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    }
   ]
  },
  {
   "title": "load dump files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "load progress",
     "type": "singlestat",
     "description": "The data import process percentage of Loader. The value range is 0% ~ 100%",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_loader_progress{task=~\"$task\",source_id=~\"$source\"}"
      }
     ]
    },
    {
     "title": "data file size",
     "type": "singlestat",
     "description": "The total size of the data files in the full data imported by Loader (including the `INSERT INTO` statement)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_loader_data_size_gauge{task=~\"$task\",source_id=~\"$source\"}"
      }
     ]
    },
    {
     "title": "dump process exits with error",
     "type": "singlestat",
     "description": "Dumper encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_dumpling_exit_with_error_count{task=~\"$task\",source_id=~\"$source\"}[30m])"
      }
     ]
    },
    {
     "title": "load process exits with error",
     "type": "singlestat",
     "description": "Loader encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_loader_exit_with_error_count{task=~\"$task\",source_id=~\"$source\"}[30m])"
      }
     ]
    },
    {
     "title": "table count",
     "type": "singlestat",
     "description": "The total number of tables in the full data imported by Loader",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_loader_table_gauge{task=~\"$task\",source_id=~\"$source\"}"
      }
     ]
    },
    {
     "title": "data file count",
     "type": "singlestat",
     "description": "The total number of data files in the full data imported by Loader (including the `INSERT INTO` statement)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_loader_data_file_gauge{task=~\"$task\",source_id=~\"$source\"}"
      }
     ]
    },
    {
     "title": "transaction execution latency",
     "type": "graph",
     "description": "The duration that Loader executes a transaction (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_txn_duration_time_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_loader_txn_duration_time_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_loader_txn_duration_time_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "statement execution latency - 90",
     "type": "graph",
     "description": "The time it takes loader to execute every statement to the downstream (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_stmt_duration_time_bucket{task=~\"$task\", type=\"begin\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "begin"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_stmt_duration_time_bucket{task=~\"$task\", type=\"stmt\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "stmt"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_stmt_duration_time_bucket{task=~\"$task\", type=\"commit\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "commit"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_loader_stmt_duration_time_bucket{task=~\"$task\", type=\"rollback\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "rollback"
      }
     ]
    }
   ]
  },
  {
   "title": "binlog replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "remaining time to sync",
     "type": "singlestat",
     "description": "The predicted remaining time it takes Syncer to be completely synchronized with the master (in minutes)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "format": "m",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_syncer_remaining_time{task=~\"$task\", source_id=~\"$source\"}"
      }
     ]
    },
    {
     "title": "replicate lag",
     "type": "singlestat",
     "description": "The latency time it takes to replicate the binlog from master to Syncer (in seconds)",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "dm_syncer_replication_lag{task=~\"$task\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "process exits with error",
     "type": "singlestat",
     "description": "The binlog replication unit process encounters an error within the DM-worker and exits",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "changes(dm_syncer_exit_with_error_count{task=~\"$task\", source_id=~\"$source\"}[30m])"
      }
     ]
    },
    {
     "title": "binlog file gap between master and syncer",
     "type": "graph",
     "description": "The number of binlog files in binlog replication unit that are behind the master",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_binlog_file{source_id=~\"$source\", task=~\"$task\", node=\"master\"} - ON(source, task, job) dm_syncer_binlog_file{source_id=~\"$source\", task=~\"$task\", node=\"syncer\"}"
      }
     ]
    },
    {
     "title": "binlog file gap between relay and syncer",
     "type": "graph",
     "description": "The number of binlog files in binlog replication unit that are behind relay",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_relay_binlog_file{instance=~\"$instance\", node=\"relay\"} - ON(instance, job) dm_syncer_binlog_file{instance=~\"$instance\", task=~\"$task\", node=\"syncer\"}"
      }
     ]
    },
    {
     "title": "binlog event QPS",
     "type": "graph",
     "description": "The number of binlog events received per unit of time (this number does not include the events that need to be skipped)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_binlog_transform_cost_count{task=~\"$task\", source_id=~\"$source\", type=\"write_rows\"}[1m])",
       "legendFormat": "insert"
      },
      {
       "expr": "rate(dm_syncer_binlog_transform_cost_count{task=~\"$task\", source_id=~\"$source\", type=\"update_rows\"}[1m])",
       "legendFormat": "update"
      },
      {
       "expr": "rate(dm_syncer_binlog_transform_cost_count{task=~\"$task\", source_id=~\"$source\", type=\"delete_rows\"}[1m])",
       "legendFormat": "delete"
      },
      {
       "expr": "rate(dm_syncer_binlog_transform_cost_count{task=~\"$task\", source_id=~\"$source\", type=\"query\"}[1m])",
       "legendFormat": "query"
      }
     ]
    },
    {
     "title": "skipped binlog event QPS",
     "type": "graph",
     "description": "The number of binlog events received per unit of time that needs to be skipped",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_skip_binlog_duration_count{task=~\"$task\", source_id=~\"$source\", type=\"rows\"}[1m])",
       "legendFormat": "rows"
      },
      {
       "expr": "rate(dm_syncer_skip_binlog_duration_count{task=~\"$task\", source_id=~\"$source\", type=\"query\"}[1m])",
       "legendFormat": "query"
      }
     ]
    },
    {
     "title": "read binlog event duration",
     "type": "graph",
     "description": "The duration that the binlog replication unit reads binlog event from the relay log or upstream MySQL (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_read_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_read_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_read_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "transform binlog event duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to parse and transform the binlog into SQL statements (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_transform_cost_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_binlog_transform_cost_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_binlog_transform_cost_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "dispatch binlog event duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to dispatch a binlog event (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_dispatch_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_dispatch_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_dispatch_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "transaction execution latency",
     "type": "graph",
     "description": "The time it takes binlog replication unit to execute the transaction to the downstream (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_txn_duration_time_bucket{task=~\"$task\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_txn_duration_time_bucket{task=~\"$task\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_txn_duration_time_bucket{task=~\"$task\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "binlog event size",
     "type": "graph",
     "description": "The size of a single binlog event that the binlog replication unit reads from relay log or upstream master",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_binlog_event_size_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_binlog_event_size_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_binlog_event_size_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "DML queue remain length",
     "type": "graph",
     "description": "The remain length of DML job queues",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_queue_size{task=~\"$task\", source_id=~\"$source\"}",
       "legendFormat": "{{queueNo}}"
      }
     ]
    },
    {
     "title": "total SQL jobs",
     "type": "graph",
     "description": "The number of newly added jobs per unit of time",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_added_jobs_total{task=~\"$task\", source_id=~\"$source\"}[1m])",
       "legendFormat": "{{queueNo}}-{{type}}"
      }
     ]
    },
    {
     "title": "finished SQL jobs",
     "type": "graph",
     "description": "The number of finished jobs per unit of time",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dm_syncer_finished_jobs_total{task=~\"$task\", source_id=~\"$source\"}[1m])",
       "legendFormat": "{{queueNo}}-{{type}}"
      }
     ]
    },
    {
     "title": "statement execution latency - 90",
     "type": "graph",
     "description": "The time it takes binlog replication unit to execute every statement to the downstream (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{task=~\"$task\", type=\"begin\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "begin"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{task=~\"$task\", type=\"stmt\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "stmt"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{task=~\"$task\", type=\"commit\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "commit"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_stmt_duration_time_bucket{task=~\"$task\", type=\"rollback\", instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "rollback"
      }
     ]
    },
    {
     "title": "add job duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to add a job to the queue (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_add_job_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_add_job_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_add_job_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "DML conflict detect duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to detect conflicts between DMLs (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_conflict_detect_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_conflict_detect_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_conflict_detect_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "skip event duration",
     "type": "graph",
     "description": "The time it takes binlog replication unit to skip a binlog event (in seconds)",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(dm_syncer_skip_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(dm_syncer_skip_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(dm_syncer_skip_binlog_duration_bucket{task=~\"$task\", source_id=~\"$source\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "unsynced tables",
     "type": "graph",
     "description": "The number of unsynced tables in the subtask",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_unsynced_table_number{source_id=~\"$source\", task=~\"$task\"}"
      }
     ]
    },
    {
     "title": "shard lock resolving",
     "type": "graph",
     "description": "Is waiting shard DDL lock to be resolved, >0 means waiting",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_shard_lock_resolving{source_id=~\"$source\", task=~\"$task\"}"
      }
     ]
    },
    {
     "title": "heartbeat update error",
     "type": "graph",
     "description": "Number of error happens when update heartbeat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dm_syncer_heartbeat_update_error"
      }
     ]
    }
   ]
  },
  {
   "title": "HA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "number of workers in different state",
     "type": "graph",
     "description": "number of worker in different states, -1 - unrecognized, 0 - offline, 1 - free, 2 - bound",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count_values(\"state\", dm_master_worker_state)"
      }
     ]
    },
    {
     "title": "workers' state",
     "type": "graph",
     "description": "state of worker, -1 - unrecognized, 0 - offline, 1 - free, 2 - bound",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (worker) (dm_master_worker_state)"
      }
     ]
    },
    {
     "title": "shard ddl error per minute",
     "type": "graph",
     "description": "number of shard DDL lock/operation error in one minute",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (task, type) (increase(dm_master_shard_ddl_error[1m]))"
      }
     ]
    },
    {
     "title": "number of pending shard ddl",
     "type": "graph",
     "description": "number of pending shard DDL in different states, Un-synced (waiting all upstream), Synced (all upstream finished, waiting all downstream)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (task, type) (dm_master_ddl_state_number)"
      }
     ]
    },
    {
     "title": "number of worker event error",
     "type": "graph",
     "description": "number of worker event error",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (dm_master_worker_event_error)"
      }
     ]
    },
    {
     "title": "number of dm-masters start leader components per minute",
     "type": "graph",
     "description": "number of dm-masters try to start leader components per minute",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "dm_master_start_leader_counter" }
     ]
    }
   ]
  }
 ]
}