apiVersion: v1
kind: Service
metadata:
  name: dm-worker
  labels:
    app: dm-worker
spec:
  ports:
    - name: dm-worker
      port: 8262
      targetPort: 8262
  selector:
    app: dm-worker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dm-worker
  labels:
    app: dm-worker
spec:
  selector:
    matchLabels:
      app: dm-worker
  serviceName: dm-worker
  replicas: 4 # 4 DM-worker instances
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: dm-worker
    spec:
      containers:
        - name: dm-worker
          image: dm:chaos # build this image in GitHub action workflow
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: dm-worker
            - mountPath: /log
              name: dm-worker-log
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8262
              name: dm-worker
          command:
            - "/dm-worker"
            - "--name=$(MY_POD_NAME)"
            - "--worker-addr=0.0.0.0:8262"
            - "--advertise-addr=$(MY_POD_NAME).dm-worker.$(MY_POD_NAMESPACE):8262"
            - "--join=dm-master-0.dm-master.$(MY_POD_NAMESPACE):8261,dm-master-1.dm-master.$(MY_POD_NAMESPACE):8261,dm-master-2.dm-master.$(MY_POD_NAMESPACE):8261"
            - "--log-file=/log/$(MY_POD_NAME).log"
          readinessProbe:
            httpGet:
              port: 8262
              path: /status
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
  volumeClaimTemplates:
    - metadata:
        name: dm-worker
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: dm-worker-log
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
