apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-dm
  labels:
    app: pod-failure-dm
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    annotationSelectors:
      chaos-mesh: "pod-failure"
  scheduler:
    cron: "@every 2m"
