apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-dm
  labels:
    app: pod-kill-dm
spec:
  action: pod-kill
  mode: one
  gracePeriod: 30
  selector:
    pods:
      default: # default namespace
        - dm-master-0
        - dm-master-1
        - dm-master-2
        - dm-worker-0
        - dm-worker-1
        - dm-worker-2
        - dm-worker-3
  scheduler:
    cron: "@every 1m"
