apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-dm
  labels:
    app: pod-kill-dm
spec:
  action: pod-kill
  mode: one
  selector:
    annotationSelectors:
      chaos-mesh: "pod-kill"
  scheduler:
    cron: "@every 1m"
