name: "\U0001F680 Feature Request"
description: I have a suggestion
labels: ["feature-request"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: more
    attributes:
      label: Teachability, Documentation, Adoption, Migration Strategy
      description: If you can, explain some scenarios how users might use this, situations it would be helpful in. Any API designs, mockups, or diagrams are also helpful.
    validations:
      required: false


