#!/bin/bash

set -eu

cur=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $cur/../_utils/test_prepare
WORK_DIR=$TEST_DIR/$TEST_NAME

function run_checkpoint() {
    prepare_data

    echo "failpoint=github.com/pingcap/dm/syncer/LoadCheckpointFailed=return(true)"
    export GO_FAILPOINTS="github.com/pingcap/dm/syncer/LoadCheckpointFailed=return(true)"

    run_dm_worker $WORK_DIR/worker1 $WORKER1_PORT $cur/conf/dm-worker1.toml
    echo "check worker 127.0.0.1:$WORKER1_PORT online"
    check_rpc_alive $cur/../bin/check_worker_online 127.0.0.1:$WORKER1_PORT
    run_dm_master $WORK_DIR/master $MASTER_PORT $cur/conf/dm-master.toml
    echo "check master 127.0.0.1:$MASTER_PORT"
    check_rpc_alive $cur/../bin/check_master_online 127.0.0.1:$MASTER_PORT

    # start task and query status, the sync unit will initial failed because load checkpoint failed.
    task_conf="$cur/conf/dm-task.yaml"
    run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
        "start-task $task_conf" \
        "\"result\": true" 2

    run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
        "query-status test" \
        "\"unit\": \"InvalidUnit\"" 1 \
        "fail to initial unit Sync of subtask test" 1

    # resume task will also initial failed
    run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
        "resume-task test" \
        "\"result\": true" 2

    run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
        "query-status test" \
        "\"unit\": \"InvalidUnit\"" 1 \
        "fail to initial unit Sync of subtask test" 1

    # reset go failpoints, and need restart dm-worker. 
    # then resume task, task will recover success.
    export GO_FAILPOINTS=''

    kill_dm_worker

    run_dm_worker $WORK_DIR/worker1 $WORKER1_PORT $cur/conf/dm-worker1.toml
    echo "check worker 127.0.0.1:$WORKER1_PORT online"
    check_rpc_alive $cur/../bin/check_worker_online 127.0.0.1:$WORKER1_PORT
    sleep 2
    
    run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
        "resume-task test" \
        "\"result\": true" 2

    check_sync_diff $WORK_DIR $cur/conf/diff_config.toml
}

#cleanup1 db_trouble
# also cleanup dm processes in case of last run failed
#cleanup2 $*
#run $*
#cleanup2 $*

#wait_process_exit dm-master.test
#wait_process_exit dm-worker.test

#echo "[$(date)] <<<<<< test case $TEST_NAME success! >>>>>>"
