#!/bin/bash

set -eu

cur=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $cur/../_utils/test_prepare
WORK_DIR=$TEST_DIR/$TEST_NAME

function run_relay_test() {
    prepare_data

    #export GO_FAILPOINTS="github.com/pingcap/dm/pkg/utils/GetGlobalVariableFailed=return(\"server_uuid\")"
    export GO_FAILPOINTS="github.com/pingcap/dm/pkg/utils/GetGlobalVariableFailed=return(\"sql_mode\")"
    run_dm_worker $WORK_DIR/worker1 $WORKER1_PORT $cur/conf/dm-worker1.toml
    echo "check worker 127.0.0.1:$WORKER1_PORT online"
    check_rpc_alive $cur/../bin/check_worker_online 127.0.0.1:$WORKER1_PORT
    run_dm_master $WORK_DIR/master $MASTER_PORT $cur/conf/dm-master.toml
    echo "check master 127.0.0.1:$MASTER_PORT"
    check_rpc_alive $cur/../bin/check_master_online 127.0.0.1:$MASTER_PORT

    run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
        "query-status" \
        "no sub task started" 1 \
        "connection is invalid" 1

    # start task and query status, the sync unit will initial failed because load checkpoint failed.
    task_conf="$cur/conf/dm-task.yaml"
    run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
        "start-task $task_conf" \
        "\"result\": true" 2

    kill_dm_worker

    # reset go failpoints, and need restart dm-worker. 
    # then resume task, task will recover success.
    export GO_FAILPOINTS=''

     run_dm_worker $WORK_DIR/worker1 $WORKER1_PORT $cur/conf/dm-worker1.toml
    echo "check worker 127.0.0.1:$WORKER1_PORT online"
    check_rpc_alive $cur/../bin/check_worker_online 127.0.0.1:$WORKER1_PORT

    sleep 1.5

    #run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
    #    "query-status test" \
    #    "no sub task started" 1 \
    #    "connection is invalid" 1

    run_dm_ctl $WORK_DIR "127.0.0.1:$MASTER_PORT" \
        "resume-task test" \
        "\"result\": true" 2

    check_sync_diff $WORK_DIR $cur/conf/diff_config.toml
}
