// Code generated by MockGen. DO NOT EDIT.
// Source: ./dmworker.pb.go

// Package pbmock is a generated GoMock package.
package pbmock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	pb "github.com/pingcap/dm/dm/pb"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	reflect "reflect"
)

// MockisSubTaskStatus_Status is a mock of isSubTaskStatus_Status interface
type MockisSubTaskStatus_Status struct {
	ctrl     *gomock.Controller
	recorder *MockisSubTaskStatus_StatusMockRecorder
}

// MockisSubTaskStatus_StatusMockRecorder is the mock recorder for MockisSubTaskStatus_Status
type MockisSubTaskStatus_StatusMockRecorder struct {
	mock *MockisSubTaskStatus_Status
}

// NewMockisSubTaskStatus_Status creates a new mock instance
func NewMockisSubTaskStatus_Status(ctrl *gomock.Controller) *MockisSubTaskStatus_Status {
	mock := &MockisSubTaskStatus_Status{ctrl: ctrl}
	mock.recorder = &MockisSubTaskStatus_StatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockisSubTaskStatus_Status) EXPECT() *MockisSubTaskStatus_StatusMockRecorder {
	return m.recorder
}

// isSubTaskStatus_Status mocks base method
func (m *MockisSubTaskStatus_Status) isSubTaskStatus_Status() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "isSubTaskStatus_Status")
}

// isSubTaskStatus_Status indicates an expected call of isSubTaskStatus_Status
func (mr *MockisSubTaskStatus_StatusMockRecorder) isSubTaskStatus_Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isSubTaskStatus_Status", reflect.TypeOf((*MockisSubTaskStatus_Status)(nil).isSubTaskStatus_Status))
}

// MarshalTo mocks base method
func (m *MockisSubTaskStatus_Status) MarshalTo(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalTo", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalTo indicates an expected call of MarshalTo
func (mr *MockisSubTaskStatus_StatusMockRecorder) MarshalTo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalTo", reflect.TypeOf((*MockisSubTaskStatus_Status)(nil).MarshalTo), arg0)
}

// Size mocks base method
func (m *MockisSubTaskStatus_Status) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (mr *MockisSubTaskStatus_StatusMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockisSubTaskStatus_Status)(nil).Size))
}

// MockisSubTaskError_Error is a mock of isSubTaskError_Error interface
type MockisSubTaskError_Error struct {
	ctrl     *gomock.Controller
	recorder *MockisSubTaskError_ErrorMockRecorder
}

// MockisSubTaskError_ErrorMockRecorder is the mock recorder for MockisSubTaskError_Error
type MockisSubTaskError_ErrorMockRecorder struct {
	mock *MockisSubTaskError_Error
}

// NewMockisSubTaskError_Error creates a new mock instance
func NewMockisSubTaskError_Error(ctrl *gomock.Controller) *MockisSubTaskError_Error {
	mock := &MockisSubTaskError_Error{ctrl: ctrl}
	mock.recorder = &MockisSubTaskError_ErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockisSubTaskError_Error) EXPECT() *MockisSubTaskError_ErrorMockRecorder {
	return m.recorder
}

// isSubTaskError_Error mocks base method
func (m *MockisSubTaskError_Error) isSubTaskError_Error() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "isSubTaskError_Error")
}

// isSubTaskError_Error indicates an expected call of isSubTaskError_Error
func (mr *MockisSubTaskError_ErrorMockRecorder) isSubTaskError_Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "isSubTaskError_Error", reflect.TypeOf((*MockisSubTaskError_Error)(nil).isSubTaskError_Error))
}

// MarshalTo mocks base method
func (m *MockisSubTaskError_Error) MarshalTo(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalTo", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalTo indicates an expected call of MarshalTo
func (mr *MockisSubTaskError_ErrorMockRecorder) MarshalTo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalTo", reflect.TypeOf((*MockisSubTaskError_Error)(nil).MarshalTo), arg0)
}

// Size mocks base method
func (m *MockisSubTaskError_Error) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (mr *MockisSubTaskError_ErrorMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockisSubTaskError_Error)(nil).Size))
}

// MockWorkerClient is a mock of WorkerClient interface
type MockWorkerClient struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerClientMockRecorder
}

// MockWorkerClientMockRecorder is the mock recorder for MockWorkerClient
type MockWorkerClientMockRecorder struct {
	mock *MockWorkerClient
}

// NewMockWorkerClient creates a new mock instance
func NewMockWorkerClient(ctrl *gomock.Controller) *MockWorkerClient {
	mock := &MockWorkerClient{ctrl: ctrl}
	mock.recorder = &MockWorkerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWorkerClient) EXPECT() *MockWorkerClientMockRecorder {
	return m.recorder
}

// StartSubTask mocks base method
func (m *MockWorkerClient) StartSubTask(ctx context.Context, in *pb.StartSubTaskRequest, opts ...grpc.CallOption) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartSubTask", varargs...)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartSubTask indicates an expected call of StartSubTask
func (mr *MockWorkerClientMockRecorder) StartSubTask(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSubTask", reflect.TypeOf((*MockWorkerClient)(nil).StartSubTask), varargs...)
}

// OperateSubTask mocks base method
func (m *MockWorkerClient) OperateSubTask(ctx context.Context, in *pb.OperateSubTaskRequest, opts ...grpc.CallOption) (*pb.OperateSubTaskResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OperateSubTask", varargs...)
	ret0, _ := ret[0].(*pb.OperateSubTaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OperateSubTask indicates an expected call of OperateSubTask
func (mr *MockWorkerClientMockRecorder) OperateSubTask(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OperateSubTask", reflect.TypeOf((*MockWorkerClient)(nil).OperateSubTask), varargs...)
}

// UpdateSubTask mocks base method
func (m *MockWorkerClient) UpdateSubTask(ctx context.Context, in *pb.UpdateSubTaskRequest, opts ...grpc.CallOption) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateSubTask", varargs...)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubTask indicates an expected call of UpdateSubTask
func (mr *MockWorkerClientMockRecorder) UpdateSubTask(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubTask", reflect.TypeOf((*MockWorkerClient)(nil).UpdateSubTask), varargs...)
}

// QueryStatus mocks base method
func (m *MockWorkerClient) QueryStatus(ctx context.Context, in *pb.QueryStatusRequest, opts ...grpc.CallOption) (*pb.QueryStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryStatus", varargs...)
	ret0, _ := ret[0].(*pb.QueryStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryStatus indicates an expected call of QueryStatus
func (mr *MockWorkerClientMockRecorder) QueryStatus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryStatus", reflect.TypeOf((*MockWorkerClient)(nil).QueryStatus), varargs...)
}

// QueryError mocks base method
func (m *MockWorkerClient) QueryError(ctx context.Context, in *pb.QueryErrorRequest, opts ...grpc.CallOption) (*pb.QueryErrorResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryError", varargs...)
	ret0, _ := ret[0].(*pb.QueryErrorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryError indicates an expected call of QueryError
func (mr *MockWorkerClientMockRecorder) QueryError(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryError", reflect.TypeOf((*MockWorkerClient)(nil).QueryError), varargs...)
}

// HandleSQLs mocks base method
func (m *MockWorkerClient) HandleSQLs(ctx context.Context, in *pb.HandleSubTaskSQLsRequest, opts ...grpc.CallOption) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HandleSQLs", varargs...)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleSQLs indicates an expected call of HandleSQLs
func (mr *MockWorkerClientMockRecorder) HandleSQLs(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSQLs", reflect.TypeOf((*MockWorkerClient)(nil).HandleSQLs), varargs...)
}

// FetchDDLInfo mocks base method
func (m *MockWorkerClient) FetchDDLInfo(ctx context.Context, opts ...grpc.CallOption) (pb.Worker_FetchDDLInfoClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchDDLInfo", varargs...)
	ret0, _ := ret[0].(pb.Worker_FetchDDLInfoClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDDLInfo indicates an expected call of FetchDDLInfo
func (mr *MockWorkerClientMockRecorder) FetchDDLInfo(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDDLInfo", reflect.TypeOf((*MockWorkerClient)(nil).FetchDDLInfo), varargs...)
}

// ExecuteDDL mocks base method
func (m *MockWorkerClient) ExecuteDDL(ctx context.Context, in *pb.ExecDDLRequest, opts ...grpc.CallOption) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteDDL", varargs...)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteDDL indicates an expected call of ExecuteDDL
func (mr *MockWorkerClientMockRecorder) ExecuteDDL(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDDL", reflect.TypeOf((*MockWorkerClient)(nil).ExecuteDDL), varargs...)
}

// BreakDDLLock mocks base method
func (m *MockWorkerClient) BreakDDLLock(ctx context.Context, in *pb.BreakDDLLockRequest, opts ...grpc.CallOption) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BreakDDLLock", varargs...)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BreakDDLLock indicates an expected call of BreakDDLLock
func (mr *MockWorkerClientMockRecorder) BreakDDLLock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BreakDDLLock", reflect.TypeOf((*MockWorkerClient)(nil).BreakDDLLock), varargs...)
}

// SwitchRelayMaster mocks base method
func (m *MockWorkerClient) SwitchRelayMaster(ctx context.Context, in *pb.SwitchRelayMasterRequest, opts ...grpc.CallOption) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SwitchRelayMaster", varargs...)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SwitchRelayMaster indicates an expected call of SwitchRelayMaster
func (mr *MockWorkerClientMockRecorder) SwitchRelayMaster(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchRelayMaster", reflect.TypeOf((*MockWorkerClient)(nil).SwitchRelayMaster), varargs...)
}

// OperateRelay mocks base method
func (m *MockWorkerClient) OperateRelay(ctx context.Context, in *pb.OperateRelayRequest, opts ...grpc.CallOption) (*pb.OperateRelayResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OperateRelay", varargs...)
	ret0, _ := ret[0].(*pb.OperateRelayResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OperateRelay indicates an expected call of OperateRelay
func (mr *MockWorkerClientMockRecorder) OperateRelay(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OperateRelay", reflect.TypeOf((*MockWorkerClient)(nil).OperateRelay), varargs...)
}

// PurgeRelay mocks base method
func (m *MockWorkerClient) PurgeRelay(ctx context.Context, in *pb.PurgeRelayRequest, opts ...grpc.CallOption) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PurgeRelay", varargs...)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeRelay indicates an expected call of PurgeRelay
func (mr *MockWorkerClientMockRecorder) PurgeRelay(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeRelay", reflect.TypeOf((*MockWorkerClient)(nil).PurgeRelay), varargs...)
}

// UpdateRelayConfig mocks base method
func (m *MockWorkerClient) UpdateRelayConfig(ctx context.Context, in *pb.UpdateRelayRequest, opts ...grpc.CallOption) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateRelayConfig", varargs...)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRelayConfig indicates an expected call of UpdateRelayConfig
func (mr *MockWorkerClientMockRecorder) UpdateRelayConfig(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRelayConfig", reflect.TypeOf((*MockWorkerClient)(nil).UpdateRelayConfig), varargs...)
}

// QueryWorkerConfig mocks base method
func (m *MockWorkerClient) QueryWorkerConfig(ctx context.Context, in *pb.QueryWorkerConfigRequest, opts ...grpc.CallOption) (*pb.QueryWorkerConfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryWorkerConfig", varargs...)
	ret0, _ := ret[0].(*pb.QueryWorkerConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWorkerConfig indicates an expected call of QueryWorkerConfig
func (mr *MockWorkerClientMockRecorder) QueryWorkerConfig(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWorkerConfig", reflect.TypeOf((*MockWorkerClient)(nil).QueryWorkerConfig), varargs...)
}

// MigrateRelay mocks base method
func (m *MockWorkerClient) MigrateRelay(ctx context.Context, in *pb.MigrateRelayRequest, opts ...grpc.CallOption) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MigrateRelay", varargs...)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigrateRelay indicates an expected call of MigrateRelay
func (mr *MockWorkerClientMockRecorder) MigrateRelay(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateRelay", reflect.TypeOf((*MockWorkerClient)(nil).MigrateRelay), varargs...)
}

// MockWorker_FetchDDLInfoClient is a mock of Worker_FetchDDLInfoClient interface
type MockWorker_FetchDDLInfoClient struct {
	ctrl     *gomock.Controller
	recorder *MockWorker_FetchDDLInfoClientMockRecorder
}

// MockWorker_FetchDDLInfoClientMockRecorder is the mock recorder for MockWorker_FetchDDLInfoClient
type MockWorker_FetchDDLInfoClientMockRecorder struct {
	mock *MockWorker_FetchDDLInfoClient
}

// NewMockWorker_FetchDDLInfoClient creates a new mock instance
func NewMockWorker_FetchDDLInfoClient(ctrl *gomock.Controller) *MockWorker_FetchDDLInfoClient {
	mock := &MockWorker_FetchDDLInfoClient{ctrl: ctrl}
	mock.recorder = &MockWorker_FetchDDLInfoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWorker_FetchDDLInfoClient) EXPECT() *MockWorker_FetchDDLInfoClientMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockWorker_FetchDDLInfoClient) Send(arg0 *pb.DDLLockInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockWorker_FetchDDLInfoClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWorker_FetchDDLInfoClient)(nil).Send), arg0)
}

// Recv mocks base method
func (m *MockWorker_FetchDDLInfoClient) Recv() (*pb.DDLInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*pb.DDLInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockWorker_FetchDDLInfoClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockWorker_FetchDDLInfoClient)(nil).Recv))
}

// Header mocks base method
func (m *MockWorker_FetchDDLInfoClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header
func (mr *MockWorker_FetchDDLInfoClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockWorker_FetchDDLInfoClient)(nil).Header))
}

// Trailer mocks base method
func (m *MockWorker_FetchDDLInfoClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer
func (mr *MockWorker_FetchDDLInfoClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockWorker_FetchDDLInfoClient)(nil).Trailer))
}

// CloseSend mocks base method
func (m *MockWorker_FetchDDLInfoClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend
func (mr *MockWorker_FetchDDLInfoClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockWorker_FetchDDLInfoClient)(nil).CloseSend))
}

// Context mocks base method
func (m *MockWorker_FetchDDLInfoClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockWorker_FetchDDLInfoClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockWorker_FetchDDLInfoClient)(nil).Context))
}

// SendMsg mocks base method
func (m_2 *MockWorker_FetchDDLInfoClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockWorker_FetchDDLInfoClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockWorker_FetchDDLInfoClient)(nil).SendMsg), m)
}

// RecvMsg mocks base method
func (m_2 *MockWorker_FetchDDLInfoClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockWorker_FetchDDLInfoClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockWorker_FetchDDLInfoClient)(nil).RecvMsg), m)
}

// MockWorkerServer is a mock of WorkerServer interface
type MockWorkerServer struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerServerMockRecorder
}

// MockWorkerServerMockRecorder is the mock recorder for MockWorkerServer
type MockWorkerServerMockRecorder struct {
	mock *MockWorkerServer
}

// NewMockWorkerServer creates a new mock instance
func NewMockWorkerServer(ctrl *gomock.Controller) *MockWorkerServer {
	mock := &MockWorkerServer{ctrl: ctrl}
	mock.recorder = &MockWorkerServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWorkerServer) EXPECT() *MockWorkerServerMockRecorder {
	return m.recorder
}

// StartSubTask mocks base method
func (m *MockWorkerServer) StartSubTask(arg0 context.Context, arg1 *pb.StartSubTaskRequest) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSubTask", arg0, arg1)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartSubTask indicates an expected call of StartSubTask
func (mr *MockWorkerServerMockRecorder) StartSubTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSubTask", reflect.TypeOf((*MockWorkerServer)(nil).StartSubTask), arg0, arg1)
}

// OperateSubTask mocks base method
func (m *MockWorkerServer) OperateSubTask(arg0 context.Context, arg1 *pb.OperateSubTaskRequest) (*pb.OperateSubTaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OperateSubTask", arg0, arg1)
	ret0, _ := ret[0].(*pb.OperateSubTaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OperateSubTask indicates an expected call of OperateSubTask
func (mr *MockWorkerServerMockRecorder) OperateSubTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OperateSubTask", reflect.TypeOf((*MockWorkerServer)(nil).OperateSubTask), arg0, arg1)
}

// UpdateSubTask mocks base method
func (m *MockWorkerServer) UpdateSubTask(arg0 context.Context, arg1 *pb.UpdateSubTaskRequest) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubTask", arg0, arg1)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubTask indicates an expected call of UpdateSubTask
func (mr *MockWorkerServerMockRecorder) UpdateSubTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubTask", reflect.TypeOf((*MockWorkerServer)(nil).UpdateSubTask), arg0, arg1)
}

// QueryStatus mocks base method
func (m *MockWorkerServer) QueryStatus(arg0 context.Context, arg1 *pb.QueryStatusRequest) (*pb.QueryStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryStatus", arg0, arg1)
	ret0, _ := ret[0].(*pb.QueryStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryStatus indicates an expected call of QueryStatus
func (mr *MockWorkerServerMockRecorder) QueryStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryStatus", reflect.TypeOf((*MockWorkerServer)(nil).QueryStatus), arg0, arg1)
}

// QueryError mocks base method
func (m *MockWorkerServer) QueryError(arg0 context.Context, arg1 *pb.QueryErrorRequest) (*pb.QueryErrorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryError", arg0, arg1)
	ret0, _ := ret[0].(*pb.QueryErrorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryError indicates an expected call of QueryError
func (mr *MockWorkerServerMockRecorder) QueryError(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryError", reflect.TypeOf((*MockWorkerServer)(nil).QueryError), arg0, arg1)
}

// HandleSQLs mocks base method
func (m *MockWorkerServer) HandleSQLs(arg0 context.Context, arg1 *pb.HandleSubTaskSQLsRequest) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSQLs", arg0, arg1)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleSQLs indicates an expected call of HandleSQLs
func (mr *MockWorkerServerMockRecorder) HandleSQLs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSQLs", reflect.TypeOf((*MockWorkerServer)(nil).HandleSQLs), arg0, arg1)
}

// FetchDDLInfo mocks base method
func (m *MockWorkerServer) FetchDDLInfo(arg0 pb.Worker_FetchDDLInfoServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDDLInfo", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchDDLInfo indicates an expected call of FetchDDLInfo
func (mr *MockWorkerServerMockRecorder) FetchDDLInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDDLInfo", reflect.TypeOf((*MockWorkerServer)(nil).FetchDDLInfo), arg0)
}

// ExecuteDDL mocks base method
func (m *MockWorkerServer) ExecuteDDL(arg0 context.Context, arg1 *pb.ExecDDLRequest) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDDL", arg0, arg1)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteDDL indicates an expected call of ExecuteDDL
func (mr *MockWorkerServerMockRecorder) ExecuteDDL(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDDL", reflect.TypeOf((*MockWorkerServer)(nil).ExecuteDDL), arg0, arg1)
}

// BreakDDLLock mocks base method
func (m *MockWorkerServer) BreakDDLLock(arg0 context.Context, arg1 *pb.BreakDDLLockRequest) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BreakDDLLock", arg0, arg1)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BreakDDLLock indicates an expected call of BreakDDLLock
func (mr *MockWorkerServerMockRecorder) BreakDDLLock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BreakDDLLock", reflect.TypeOf((*MockWorkerServer)(nil).BreakDDLLock), arg0, arg1)
}

// SwitchRelayMaster mocks base method
func (m *MockWorkerServer) SwitchRelayMaster(arg0 context.Context, arg1 *pb.SwitchRelayMasterRequest) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchRelayMaster", arg0, arg1)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SwitchRelayMaster indicates an expected call of SwitchRelayMaster
func (mr *MockWorkerServerMockRecorder) SwitchRelayMaster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchRelayMaster", reflect.TypeOf((*MockWorkerServer)(nil).SwitchRelayMaster), arg0, arg1)
}

// OperateRelay mocks base method
func (m *MockWorkerServer) OperateRelay(arg0 context.Context, arg1 *pb.OperateRelayRequest) (*pb.OperateRelayResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OperateRelay", arg0, arg1)
	ret0, _ := ret[0].(*pb.OperateRelayResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OperateRelay indicates an expected call of OperateRelay
func (mr *MockWorkerServerMockRecorder) OperateRelay(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OperateRelay", reflect.TypeOf((*MockWorkerServer)(nil).OperateRelay), arg0, arg1)
}

// PurgeRelay mocks base method
func (m *MockWorkerServer) PurgeRelay(arg0 context.Context, arg1 *pb.PurgeRelayRequest) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeRelay", arg0, arg1)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgeRelay indicates an expected call of PurgeRelay
func (mr *MockWorkerServerMockRecorder) PurgeRelay(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeRelay", reflect.TypeOf((*MockWorkerServer)(nil).PurgeRelay), arg0, arg1)
}

// UpdateRelayConfig mocks base method
func (m *MockWorkerServer) UpdateRelayConfig(arg0 context.Context, arg1 *pb.UpdateRelayRequest) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRelayConfig", arg0, arg1)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRelayConfig indicates an expected call of UpdateRelayConfig
func (mr *MockWorkerServerMockRecorder) UpdateRelayConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRelayConfig", reflect.TypeOf((*MockWorkerServer)(nil).UpdateRelayConfig), arg0, arg1)
}

// QueryWorkerConfig mocks base method
func (m *MockWorkerServer) QueryWorkerConfig(arg0 context.Context, arg1 *pb.QueryWorkerConfigRequest) (*pb.QueryWorkerConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWorkerConfig", arg0, arg1)
	ret0, _ := ret[0].(*pb.QueryWorkerConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWorkerConfig indicates an expected call of QueryWorkerConfig
func (mr *MockWorkerServerMockRecorder) QueryWorkerConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWorkerConfig", reflect.TypeOf((*MockWorkerServer)(nil).QueryWorkerConfig), arg0, arg1)
}

// MigrateRelay mocks base method
func (m *MockWorkerServer) MigrateRelay(arg0 context.Context, arg1 *pb.MigrateRelayRequest) (*pb.CommonWorkerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MigrateRelay", arg0, arg1)
	ret0, _ := ret[0].(*pb.CommonWorkerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MigrateRelay indicates an expected call of MigrateRelay
func (mr *MockWorkerServerMockRecorder) MigrateRelay(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MigrateRelay", reflect.TypeOf((*MockWorkerServer)(nil).MigrateRelay), arg0, arg1)
}

// MockWorker_FetchDDLInfoServer is a mock of Worker_FetchDDLInfoServer interface
type MockWorker_FetchDDLInfoServer struct {
	ctrl     *gomock.Controller
	recorder *MockWorker_FetchDDLInfoServerMockRecorder
}

// MockWorker_FetchDDLInfoServerMockRecorder is the mock recorder for MockWorker_FetchDDLInfoServer
type MockWorker_FetchDDLInfoServerMockRecorder struct {
	mock *MockWorker_FetchDDLInfoServer
}

// NewMockWorker_FetchDDLInfoServer creates a new mock instance
func NewMockWorker_FetchDDLInfoServer(ctrl *gomock.Controller) *MockWorker_FetchDDLInfoServer {
	mock := &MockWorker_FetchDDLInfoServer{ctrl: ctrl}
	mock.recorder = &MockWorker_FetchDDLInfoServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWorker_FetchDDLInfoServer) EXPECT() *MockWorker_FetchDDLInfoServerMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockWorker_FetchDDLInfoServer) Send(arg0 *pb.DDLInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockWorker_FetchDDLInfoServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWorker_FetchDDLInfoServer)(nil).Send), arg0)
}

// Recv mocks base method
func (m *MockWorker_FetchDDLInfoServer) Recv() (*pb.DDLLockInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*pb.DDLLockInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockWorker_FetchDDLInfoServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockWorker_FetchDDLInfoServer)(nil).Recv))
}

// SetHeader mocks base method
func (m *MockWorker_FetchDDLInfoServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader
func (mr *MockWorker_FetchDDLInfoServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockWorker_FetchDDLInfoServer)(nil).SetHeader), arg0)
}

// SendHeader mocks base method
func (m *MockWorker_FetchDDLInfoServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader
func (mr *MockWorker_FetchDDLInfoServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockWorker_FetchDDLInfoServer)(nil).SendHeader), arg0)
}

// SetTrailer mocks base method
func (m *MockWorker_FetchDDLInfoServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer
func (mr *MockWorker_FetchDDLInfoServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockWorker_FetchDDLInfoServer)(nil).SetTrailer), arg0)
}

// Context mocks base method
func (m *MockWorker_FetchDDLInfoServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockWorker_FetchDDLInfoServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockWorker_FetchDDLInfoServer)(nil).Context))
}

// SendMsg mocks base method
func (m_2 *MockWorker_FetchDDLInfoServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockWorker_FetchDDLInfoServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockWorker_FetchDDLInfoServer)(nil).SendMsg), m)
}

// RecvMsg mocks base method
func (m_2 *MockWorker_FetchDDLInfoServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockWorker_FetchDDLInfoServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockWorker_FetchDDLInfoServer)(nil).RecvMsg), m)
}
