/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DMMetaListerExpansion allows custom methods to be added to
// DMMetaLister.
type DMMetaListerExpansion interface{}

// DMMetaNamespaceListerExpansion allows custom methods to be added to
// DMMetaNamespaceLister.
type DMMetaNamespaceListerExpansion interface{}

// DMNodeListerExpansion allows custom methods to be added to
// DMNodeLister.
type DMNodeListerExpansion interface{}

// DMNodeNamespaceListerExpansion allows custom methods to be added to
// DMNodeNamespaceLister.
type DMNodeNamespaceListerExpansion interface{}

// DMTaskListerExpansion allows custom methods to be added to
// DMTaskLister.
type DMTaskListerExpansion interface{}

// DMTaskNamespaceListerExpansion allows custom methods to be added to
// DMTaskNamespaceLister.
type DMTaskNamespaceListerExpansion interface{}
